//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Aircrew1 {
            get {
                object obj = ResourceManager.GetObject("Aircrew1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Aires1 {
            get {
                object obj = ResourceManager.GetObject("Aires1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Aurorite1 {
            get {
                object obj = ResourceManager.GetObject("Aurorite1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Boulda1 {
            get {
                object obj = ResourceManager.GetObject("Boulda1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bronze_Construct1 {
            get {
                object obj = ResourceManager.GetObject("Bronze_Construct1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cion1 {
            get {
                object obj = ResourceManager.GetObject("Cion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cire1 {
            get {
                object obj = ResourceManager.GetObject("Cire1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cloudd1 {
            get {
                object obj = ResourceManager.GetObject("Cloudd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Combustor1 {
            get {
                object obj = ResourceManager.GetObject("Combustor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Corpse1 {
            get {
                object obj = ResourceManager.GetObject("Corpse1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Drift1 {
            get {
                object obj = ResourceManager.GetObject("Drift1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Electreel1 {
            get {
                object obj = ResourceManager.GetObject("Electreel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ent1 {
            get {
                object obj = ResourceManager.GetObject("Ent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Excitrik1 {
            get {
                object obj = ResourceManager.GetObject("Excitrik1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Floikes1 {
            get {
                object obj = ResourceManager.GetObject("Floikes1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gunnery1 {
            get {
                object obj = ResourceManager.GetObject("Gunnery1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Guns1 {
            get {
                object obj = ResourceManager.GetObject("Guns1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hellion1 {
            get {
                object obj = ResourceManager.GetObject("Hellion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hermit1 {
            get {
                object obj = ResourceManager.GetObject("Hermit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hiss1 {
            get {
                object obj = ResourceManager.GetObject("Hiss1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icekerzo1 {
            get {
                object obj = ResourceManager.GetObject("Icekerzo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Incubat1 {
            get {
                object obj = ResourceManager.GetObject("Incubat1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Iron_Construct1 {
            get {
                object obj = ResourceManager.GetObject("Iron_Construct1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kitticar1 {
            get {
                object obj = ResourceManager.GetObject("Kitticar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kommion1 {
            get {
                object obj = ResourceManager.GetObject("Kommion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Komsaikai1 {
            get {
                object obj = ResourceManager.GetObject("Komsaikai1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Laziclaw1 {
            get {
                object obj = ResourceManager.GetObject("Laziclaw1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mantid1 {
            get {
                object obj = ResourceManager.GetObject("Mantid1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mountking1 {
            get {
                object obj = ResourceManager.GetObject("Mountking1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Namu1 {
            get {
                object obj = ResourceManager.GetObject("Namu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orite1 {
            get {
                object obj = ResourceManager.GetObject("Orite1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Oryion1 {
            get {
                object obj = ResourceManager.GetObject("Oryion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pebblia1 {
            get {
                object obj = ResourceManager.GetObject("Pebblia1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Piss_Puddle1 {
            get {
                object obj = ResourceManager.GetObject("Piss_Puddle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Poliba1 {
            get {
                object obj = ResourceManager.GetObject("Poliba1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ponder1 {
            get {
                object obj = ResourceManager.GetObject("Ponder1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ravipion1 {
            get {
                object obj = ResourceManager.GetObject("Ravipion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rockin1 {
            get {
                object obj = ResourceManager.GetObject("Rockin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rocky1 {
            get {
                object obj = ResourceManager.GetObject("Rocky1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Roughion1 {
            get {
                object obj = ResourceManager.GetObject("Roughion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Scorpo1 {
            get {
                object obj = ResourceManager.GetObject("Scorpo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Skyte1 {
            get {
                object obj = ResourceManager.GetObject("Skyte1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Smogg1 {
            get {
                object obj = ResourceManager.GetObject("Smogg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snowball1 {
            get {
                object obj = ResourceManager.GetObject("Snowball1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snowstrom1 {
            get {
                object obj = ResourceManager.GetObject("Snowstrom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SteelCons1 {
            get {
                object obj = ResourceManager.GetObject("SteelCons1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stickum1 {
            get {
                object obj = ResourceManager.GetObject("Stickum1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Streamain1 {
            get {
                object obj = ResourceManager.GetObject("Streamain1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Supresloth1 {
            get {
                object obj = ResourceManager.GetObject("Supresloth1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tankimnida1 {
            get {
                object obj = ResourceManager.GetObject("Tankimnida1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Thormion1 {
            get {
                object obj = ResourceManager.GetObject("Thormion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toasti1 {
            get {
                object obj = ResourceManager.GetObject("Toasti1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Treep1 {
            get {
                object obj = ResourceManager.GetObject("Treep1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vinyan1 {
            get {
                object obj = ResourceManager.GetObject("Vinyan1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volchick1 {
            get {
                object obj = ResourceManager.GetObject("Volchick1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volcipeon1 {
            get {
                object obj = ResourceManager.GetObject("Volcipeon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vRaptor1 {
            get {
                object obj = ResourceManager.GetObject("vRaptor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Waterwing1 {
            get {
                object obj = ResourceManager.GetObject("Waterwing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wraith1 {
            get {
                object obj = ResourceManager.GetObject("Wraith1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zapawk1 {
            get {
                object obj = ResourceManager.GetObject("Zapawk1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombones1 {
            get {
                object obj = ResourceManager.GetObject("Zombones1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
