// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.832
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
// TODO: Option Strict On ... Warning!!! not translated
// TODO: Option Explicit On ... Warning!!! not translated
namespace My.Resources {
    using System;
    
    
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    // ''<summary>
    // ''  A strongly-typed resource class, for looking up localized strings, etc.
    // ''</summary>
    [Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [Global.System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    class textures {
        
        private static Global.System.Resources.ResourceManager resourceMan;
        
        private static Global.System.Globalization.CultureInfo resourceCulture;
        
        [Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal textures() {
            base.New;
        }
        
        // ''<summary>
        // ''  Returns the cached ResourceManager instance used by this class.
        // ''</summary>
        [Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static Global.System.Resources.ResourceManager ResourceManager {
            get {
                ReferenceEquals(resourceMan, null);
                Global.System.Resources.ResourceManager temp = new Global.System.Resources.ResourceManager("Battle_.textures", typeof(textures).Assembly);
                resourceMan = temp;
            }
        }
    }
}
SetresourceCulture = value;
EndSetEndPropertyEndclass End {
}

    
    internal static System.Drawing.Bitmap Aircrew {
        get {
            object obj = ResourceManager.GetObject("Aircrew", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Aires {
        get {
            object obj = ResourceManager.GetObject("Aires", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Aurorite {
        get {
            object obj = ResourceManager.GetObject("Aurorite", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Boulda {
        get {
            object obj = ResourceManager.GetObject("Boulda", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap BronzeCons {
        get {
            object obj = ResourceManager.GetObject("BronzeCons", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Cion {
        get {
            object obj = ResourceManager.GetObject("Cion", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Cire {
        get {
            object obj = ResourceManager.GetObject("Cire", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Cloudd {
        get {
            object obj = ResourceManager.GetObject("Cloudd", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Combustor {
        get {
            object obj = ResourceManager.GetObject("Combustor", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Corpse {
        get {
            object obj = ResourceManager.GetObject("Corpse", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Drift {
        get {
            object obj = ResourceManager.GetObject("Drift", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Electreel {
        get {
            object obj = ResourceManager.GetObject("Electreel", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Ent {
        get {
            object obj = ResourceManager.GetObject("Ent", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Excitrik {
        get {
            object obj = ResourceManager.GetObject("Excitrik", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Floikes {
        get {
            object obj = ResourceManager.GetObject("Floikes", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Gunnery {
        get {
            object obj = ResourceManager.GetObject("Gunnery", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Guns {
        get {
            object obj = ResourceManager.GetObject("Guns", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Hellion {
        get {
            object obj = ResourceManager.GetObject("Hellion", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Hermit {
        get {
            object obj = ResourceManager.GetObject("Hermit", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Hiss {
        get {
            object obj = ResourceManager.GetObject("Hiss", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Icekerzo {
        get {
            object obj = ResourceManager.GetObject("Icekerzo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Incubat {
        get {
            object obj = ResourceManager.GetObject("Incubat", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap IronCons {
        get {
            object obj = ResourceManager.GetObject("IronCons", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Kitticar {
        get {
            object obj = ResourceManager.GetObject("Kitticar", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Kommion {
        get {
            object obj = ResourceManager.GetObject("Kommion", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Komsaikai {
        get {
            object obj = ResourceManager.GetObject("Komsaikai", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Laziclaw {
        get {
            object obj = ResourceManager.GetObject("Laziclaw", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap mantid {
        get {
            object obj = ResourceManager.GetObject("mantid", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Mountking {
        get {
            object obj = ResourceManager.GetObject("Mountking", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Namu {
        get {
            object obj = ResourceManager.GetObject("Namu", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Orite {
        get {
            object obj = ResourceManager.GetObject("Orite", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Oryion {
        get {
            object obj = ResourceManager.GetObject("Oryion", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Pebblia {
        get {
            object obj = ResourceManager.GetObject("Pebblia", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap PissPuddle {
        get {
            object obj = ResourceManager.GetObject("PissPuddle", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Poliba {
        get {
            object obj = ResourceManager.GetObject("Poliba", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Ponder {
        get {
            object obj = ResourceManager.GetObject("Ponder", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Ravipion {
        get {
            object obj = ResourceManager.GetObject("Ravipion", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Rockin {
        get {
            object obj = ResourceManager.GetObject("Rockin", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Rocky {
        get {
            object obj = ResourceManager.GetObject("Rocky", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Roughion {
        get {
            object obj = ResourceManager.GetObject("Roughion", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Scorpo {
        get {
            object obj = ResourceManager.GetObject("Scorpo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Skyte {
        get {
            object obj = ResourceManager.GetObject("Skyte", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Smogg {
        get {
            object obj = ResourceManager.GetObject("Smogg", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Snowball {
        get {
            object obj = ResourceManager.GetObject("Snowball", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Snowstrom {
        get {
            object obj = ResourceManager.GetObject("Snowstrom", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap SteelCons {
        get {
            object obj = ResourceManager.GetObject("SteelCons", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Stickum {
        get {
            object obj = ResourceManager.GetObject("Stickum", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Streamain {
        get {
            object obj = ResourceManager.GetObject("Streamain", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Supresloth {
        get {
            object obj = ResourceManager.GetObject("Supresloth", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Tankimnida {
        get {
            object obj = ResourceManager.GetObject("Tankimnida", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Thormion {
        get {
            object obj = ResourceManager.GetObject("Thormion", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Toasti {
        get {
            object obj = ResourceManager.GetObject("Toasti", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Treep {
        get {
            object obj = ResourceManager.GetObject("Treep", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Vinyan {
        get {
            object obj = ResourceManager.GetObject("Vinyan", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Volchick {
        get {
            object obj = ResourceManager.GetObject("Volchick", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Volcipeon {
        get {
            object obj = ResourceManager.GetObject("Volcipeon", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap vRaptor {
        get {
            object obj = ResourceManager.GetObject("vRaptor", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Waterwing {
        get {
            object obj = ResourceManager.GetObject("Waterwing", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Wraith {
        get {
            object obj = ResourceManager.GetObject("Wraith", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Zapawk {
        get {
            object obj = ResourceManager.GetObject("Zapawk", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    internal static System.Drawing.Bitmap Zombones {
        get {
            object obj = ResourceManager.GetObject("Zombones", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }

